# Generated by Django 2.2 on 2019-05-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20190503_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
